name: release
on:
  push:
    tags:
      - v*
  pull_request: # TODO: remove

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build binary for Docker
        run: |
          make build
          chmod +x ./autotag/autotag

      - name: Install rpm
        run: |
          sudo apt-get -qqy update && sudo apt-get -qqy install rpm

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWD }}

#      - name: Deploy Autotag Release
#        # TODO(vtopc): switch to the `goreleaser/goreleaser-action` GHA?
#        run: |
#          curl -sL https://git.io/goreleaser | bash -s -- --parallelism=2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          QUAY_USER: ${{ secrets.QUAY_USER }}
#          QUAY_PASSWD: ${{ secrets.QUAY_PASSWD }}
